@startuml
class Connect4
class Board{
    -GRID:Array
    getGrid()
    putToken()
}
class GameView {
}
class PlayerView {
}
class BoardView {
    show()
}
class Player {
    -color
    getToken()
    getColor()
}
class Cell {
    -token
    getToken()
    setToken()
}
class Token
enum Color{
}

Connect4 *--> "1" GameView
GameView *--> "2" PlayerView
GameView *--> "1" BoardView
PlayerView *--> "1" Player
BoardView *--> "1" Board
Token *--> Color
Player o--> "0..21" Token
Player ..> Color

Board *--> "0..6x7" Cell
Cell o--> "1" Token
@enduml